import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ── Stitch SpotHunt Design System ──
        'surface': '#1b110a',
        'surface-variant': '#3f3229',
        'surface-container': '#281d15',
        'surface-container-low': '#241912',
        'surface-container-high': '#33281f',
        'surface-container-highest': '#3f3229',
        'surface-container-lowest': '#150c06',
        'surface-dim': '#1b110a',
        'surface-bright': '#43372e',
        'surface-tint': '#ffb77d',
        'background': '#1b110a',
        'on-background': '#f3dfd1',
        'primary': '#ffb77d',
        'primary-container': '#ff8c00',
        'primary-fixed': '#ffdcc3',
        'primary-fixed-dim': '#ffb77d',
        'on-primary': '#4d2600',
        'on-primary-container': '#623200',
        'on-primary-fixed': '#2f1500',
        'on-primary-fixed-variant': '#6e3900',
        'inverse-primary': '#904d00',
        'secondary': '#c6c4df',
        'secondary-container': '#47475d',
        'secondary-fixed': '#e2e0fc',
        'secondary-fixed-dim': '#c6c4df',
        'on-secondary': '#2f2e43',
        'on-secondary-fixed': '#1a1a2e',
        'on-secondary-fixed-variant': '#45455b',
        'on-secondary-container': '#b8b6d0',
        'tertiary': '#e9c400',
        'tertiary-container': '#c7a800',
        'tertiary-fixed': '#ffe16d',
        'tertiary-fixed-dim': '#e9c400',
        'on-tertiary': '#3a3000',
        'on-tertiary-container': '#4b3e00',
        'on-tertiary-fixed': '#221b00',
        'on-tertiary-fixed-variant': '#544600',
        'on-surface': '#f3dfd1',
        'on-surface-variant': '#ddc1ae',
        'outline': '#a48c7a',
        'outline-variant': '#564334',
        'inverse-surface': '#f3dfd1',
        'inverse-on-surface': '#3a2e25',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        // ── Legacy tokens (kept for other pages) ──
        kp: {
          DEFAULT: '#7132f5',
          dark: '#5741d8',
          deep: '#5b1ecf',
          subtle: 'rgba(133,91,251,0.16)',
          faint: 'rgba(133,91,251,0.08)',
        },
        knear: '#101114',
        kgray: {
          DEFAULT: '#686b82',
          light: '#9497a9',
          border: '#dedee5',
          bg: '#f7f7f9',
        },
        kgreen: {
          DEFAULT: '#149e61',
          dark: '#026b3f',
          bg: 'rgba(20,158,97,0.16)',
        },
      },
      spacing: {
        'touch-target-min': '48px',
        'gutter': '16px',
        'safe-margin': '20px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        display: ['Montserrat', 'sans-serif'],
        headline: ['Montserrat', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        ui: ['Inter', 'Helvetica Neue', 'Arial', 'sans-serif'],
      },
      boxShadow: {
        kraken: 'rgba(0,0,0,0.03) 0px 4px 24px',
        'kraken-micro': 'rgba(16,24,40,0.04) 0px 1px 4px',
        'kraken-up': '0 -4px 24px rgba(0,0,0,0.08)',
      },
    },
  },
  plugins: [],
}

export default config
